name: Deploy Docker to the DockerHub
on:
  push:
    branches:
      ["main"]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    -
      name: Install Poetry
      run: pip install poetry
    -
      name: Get project version
      run: echo "APP_VERSION=$(poetry version -s)" >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/photo-django:${{ env.APP_VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/photo-django:latest
