# Generated by Django 4.2.2 on 2023-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="First Name"
            ),
        ),
    ]
