apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
  labels:
    app: postgres
data:
  DATABASE_NAME: photo-db
  DATABASE_USER: photoadmin
  DATABASE_PASSWORD: photoadmin
  DATABASE_HOST: postgres-cluster-ip-service  # Name of postgres Service
  DATABASE_PORT: "5432"
  SECRET_KEY: secret-value
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "*"
  REACT_APP_API_URL: "http://0.0.0.0:8000"