# Job
apiVersion: batch/v1
kind: Job
metadata:
  name: django-job
spec:
  template:
    spec:
      containers:
      - name: django-job-container
        image: vitaliyshvab/django-app:latest
        command: ["bash", "-c", "/usr/src/app/api/entrypoint.sh"]
        env:
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: SECRET_KEY
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DEBUG
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_PORT
      restartPolicy: Never
  backoffLimit: 4
