apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
    spec:
      containers:
        - name: django-container
          image: vitaliyshvab/django-app:latest
          ports:
            - containerPort: 8000
          command: ["bash", "-c", "python manage.py runserver"]
          env:
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: SECRET_KEY
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DEBUG
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE_PORT

---

# Cluster IP Service
apiVersion: v1
kind: Service
metadata:
  name: django-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: django
  ports:
    - port: 8000
      targetPort: 8000