name: Lint
on:
  pull_request:
    branches:
      ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages via YARN
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint src/
